# Generated by Django 2.2.5 on 2020-01-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='ads/%Y/%m-%d/')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user_is_reject',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_submit',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='scientist',
            field=models.NullBooleanField(default=False),
        ),
    ]
