# Generated by Django 2.2.5 on 2020-01-18 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2020, 1, 18, 14, 48, 22, 183369), verbose_name='Дата публикации'),
        ),
    ]
